### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by maiktheknife** [SharedKnowledge/SharkOISIndoor#1]
Also wenn die Stackoverflow Antwort mit dem Satz:

**Be careful that this will create an "alternate reality" for people who have already fetch/pulled/cloned from the remote repository. But in fact, it's quite simple:**

beginnt, sollte ich lieber nichts mehr versuchen.
Ich habe es iwie geschafft, alle remote Branches zu löschen.
Der einzige vorhandene war nun ein neuer Branch, den ich eigentlich hinzufügen wollte.

Den Branche master konnte ich wiederherstellen, den listview branch allerdings nicht.
Ich weiß jetzt auch nicht zu 100% ob jetzt nicht irgendetwas anderes als zuvor / verloren gegangen ist.

Und wie kann man den default branch wieder auf master setzten?

Schaut es euch doch mal bitte an.

Mit Bitte um Entschuldigung. 
Max M

**Comment by maikmueller** [comment]
Max, ich habe meine Remotes (Master/Listview) gelöscht um etwas Ordnung reinzubekommen. Vielleicht weißt du es, wie ich einen Remotebranch von zb Master in irgendwas anderes umbenennen kann? Ich gehe davon aus, dass jeder nur mit seinem eigenen Branch arbeitet, sonst endet das doch im Chaos. 😉

**Comment by maiktheknife** [comment]
also das mit dem umbennen weiß ich leider nicht, 
mein ziel war ja der eigene branch (userapp), aber ich bin dran gescheitert -.-

**Comment by maikmueller** [comment]
Und dann müsste der Userapp Branch auch erstmal gelöscht werden. Oder zumindest will ich erstmal das Vermessungstool löschen und einen neuen Remotebranch für Sören und mich mit aktuellen Code erstellen

**Comment by maiktheknife** [comment]
Kann ich machen, wäre ja dann hier erstmal wieder komplett leer.

**Comment by maikmueller** [comment]
Das ist kein Problem. Lokal ist alles Safe. Ohne löschen bekommen wir da keine Ordnung rein. 😉

**Comment by maiktheknife** [comment]
Ist leer.
